#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#chmod -R o-rwx "$install_dir"
#chown -R $app:www-data "$install_dir"
chmod +x "$install_dir/hbbr"
chmod +x "$install_dir/hbbs"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_systemd --service=rustdeskrelay --template=rustdeskrelay.service
ynh_config_add_systemd --service=rustdesksignal --template=rustdesksignal.service

yunohost service add rustdeskrelay --description="Rustdesk Relay Server" --log="/var/log/$app/$app.log"
yunohost service add rustdesksignal --description="Rustdesk Signal Server" --log="/var/log/$app/$app.log"

mkdir -p /var/log/$app
touch /var/log/$app/$app.log
#chown $app -R /var/log/$app

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=rustdeskrelay --action="start" --log_path="systemd"
ynh_systemctl --service=rustdesksignal --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
