#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
# REMOVE SYSTEMD SERVICE 
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

if ynh_exec_warn_less yunohost service status rustdeskrelay >/dev/null
then
	ynh_script_progression --message="Removing rustdeskrelay service integration..." --weight=1
	yunohost service remove rustdeskrelay
fi
if ynh_exec_warn_less yunohost service status rustdesksignal >/dev/null
then
	ynh_script_progression --message="Removing rustdesksignal service integration..." --weight=1
	yunohost service remove rustdesksignal
fi

ynh_remove_systemd_config --service=rustdeskrelay
ynh_remove_systemd_config --service=rustdesksignal

ynh_remove_logrotate


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
