#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status rustdeskrelay >/dev/null; then
	yunohost service remove rustdeskrelay
fi
if ynh_hide_warnings yunohost service status rustdesksignal >/dev/null; then
	yunohost service remove rustdesksignal
fi

ynh_config_remove_systemd rustdeskrelay
ynh_config_remove_systemd rustdesksignal

ynh_config_remove_logrotate

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
