#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chmod +x "$install_dir/hbbr"
chmod +x "$install_dir/hbbs"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/systemd/system/rustdeskrelay.service"
systemctl enable rustdeskrelay.service --quiet

ynh_restore "/etc/systemd/system/rustdesksignal.service"
systemctl enable rustdesksignal.service --quiet

mkdir -p /var/log/$app
touch /var/log/$app/$app.log

ynh_restore "/etc/logrotate.d/$app"

# According to the doc (no web client for now) https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/install/#ports
# TCP: 21115 21116 21117
# UDP: 21116
yunohost service add rustdeskrelay --description="Rustdesk Relay Server" --log="/var/log/$app/$app.log" --needs_exposed_ports 21117
yunohost service add rustdesksignal --description="Rustdesk Signal Server" --log="/var/log/$app/$app.log" --needs_exposed_ports 21115 21116

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service=rustdeskrelay --action="start" --log_path="systemd"
ynh_systemctl --service=rustdesksignal --action="start" --log_path="systemd"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
