#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=rustdeskrelay --action="stop" --log_path="systemd"
ynh_systemctl --service=rustdesksignal --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --keep="id_ed25519.pub id_ed25519"

chmod +x "$install_dir/hbbr"
chmod +x "$install_dir/hbbs"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_systemd --service=rustdeskrelay --template=rustdeskrelay.service
ynh_config_add_systemd --service=rustdesksignal --template=rustdesksignal.service

# According to the doc (no web client for now) https://rustdesk.com/docs/en/self-host/rustdesk-server-oss/install/#ports
# TCP: 21115 21116 21117
# UDP: 21116
yunohost service add rustdeskrelay --description="Rustdesk Relay Server" --log="/var/log/$app/$app.log" --needs_exposed_ports 21117
yunohost service add rustdesksignal --description="Rustdesk Signal Server" --log="/var/log/$app/$app.log" --needs_exposed_ports 21115 21116

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=rustdeskrelay --action="start" --log_path="systemd"
ynh_systemctl --service=rustdesksignal --action="start" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
